<?php
/**
 * CampaignTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  GuestNetworks
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Guest Networks API
 *
 * This is the public API for the [Guest Networks platform](https://www.mywifinetworks.com).  All requests must include an App Secret Key for authentication. To get your App Secret Key: 1. Log in to your MyWiFi Control Panel 1. Navigate to Branding section 1. Note your API key, located in the App Secret Key field   <br/> # Available SDKs [PHP API Client](https://github.com/MyWiFiNetworks/PublicAPI-PHP)
 *
 * OpenAPI spec version: 1.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.19
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace GuestNetworks;

/**
 * CampaignTest Class Doc Comment
 *
 * @category    Class
 * @description Campaign
 * @package     GuestNetworks
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class CampaignTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Campaign"
     */
    public function testCampaign()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "campaign_id"
     */
    public function testPropertyCampaignId()
    {
    }

    /**
     * Test attribute "template_campaign_id"
     */
    public function testPropertyTemplateCampaignId()
    {
    }

    /**
     * Test attribute "login_options"
     */
    public function testPropertyLoginOptions()
    {
    }

    /**
     * Test attribute "ssid"
     */
    public function testPropertySsid()
    {
    }

    /**
     * Test attribute "text_color"
     */
    public function testPropertyTextColor()
    {
    }

    /**
     * Test attribute "background"
     */
    public function testPropertyBackground()
    {
    }

    /**
     * Test attribute "footer_text"
     */
    public function testPropertyFooterText()
    {
    }

    /**
     * Test attribute "title_text"
     */
    public function testPropertyTitleText()
    {
    }

    /**
     * Test attribute "custom_terms"
     */
    public function testPropertyCustomTerms()
    {
    }

    /**
     * Test attribute "redirect_url"
     */
    public function testPropertyRedirectUrl()
    {
    }

    /**
     * Test attribute "login_facebook"
     */
    public function testPropertyLoginFacebook()
    {
    }

    /**
     * Test attribute "login_custom"
     */
    public function testPropertyLoginCustom()
    {
    }

    /**
     * Test attribute "login_twitter"
     */
    public function testPropertyLoginTwitter()
    {
    }

    /**
     * Test attribute "login_instagram"
     */
    public function testPropertyLoginInstagram()
    {
    }

    /**
     * Test attribute "login_linkedin"
     */
    public function testPropertyLoginLinkedin()
    {
    }
}
