<?php
/**
 * AnalyticsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  GuestNetworks
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Guest Networks API
 *
 * This is the public API for the [Guest Networks platform](https://www.mywifinetworks.com).  All requests must include an App Secret Key for authentication. To get your App Secret Key: 1. Log in to your MyWiFi Control Panel 1. Navigate to Branding section 1. Note your API key, located in the App Secret Key field   <br/> # Available SDKs [PHP API Client](https://github.com/MyWiFiNetworks/PublicAPI-PHP)
 *
 * OpenAPI spec version: 1.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.19
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace GuestNetworks;

use GuestNetworks\Configuration;
use GuestNetworks\ApiException;
use GuestNetworks\ObjectSerializer;

/**
 * AnalyticsApiTest Class Doc Comment
 *
 * @category Class
 * @package  GuestNetworks
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class AnalyticsApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for averageBandwidthUsage
     *
     * Retrieve average bandwidth used for a Location in bytes.
     *
     */
    public function testAverageBandwidthUsage()
    {
    }

    /**
     * Test case for averageSessionTime
     *
     * Retrieve average visit duration for a Location in seconds.
     *
     */
    public function testAverageSessionTime()
    {
    }

    /**
     * Test case for getSocialLogins
     *
     * Retrieve aggregated guest logins for a Location.
     *
     */
    public function testGetSocialLogins()
    {
    }

    /**
     * Test case for getVisits
     *
     * Retrieve aggregated visit data for a Location.
     *
     */
    public function testGetVisits()
    {
    }
}
