<?php
/**
 * CampaignsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  GuestNetworks
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Guest Networks API
 *
 * This is the public API for the [Guest Networks platform](https://www.mywifinetworks.com).  All requests must include an App Secret Key for authentication. To get your App Secret Key: 1. Log in to your MyWiFi Control Panel 1. Navigate to Branding section 1. Note your API key, located in the App Secret Key field
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.10
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace GuestNetworks;

use GuestNetworks\Configuration;
use GuestNetworks\ApiException;
use GuestNetworks\ObjectSerializer;

/**
 * CampaignsApiTest Class Doc Comment
 *
 * @category Class
 * @package  GuestNetworks
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class CampaignsApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for campaignList
     *
     * Retrieve list of all Campaigns.
     *
     */
    public function testCampaignList()
    {
    }

    /**
     * Test case for createOrUpdateCampaign
     *
     * Create or Update a Campaign.
     *
     */
    public function testCreateOrUpdateCampaign()
    {
    }

    /**
     * Test case for deleteCampaign
     *
     * Delete a Campaign.
     *
     */
    public function testDeleteCampaign()
    {
    }

    /**
     * Test case for getCampaign
     *
     * Retrieve data for multiple or single Campaign(s).
     *
     */
    public function testGetCampaign()
    {
    }
}
