<?php
/**
 * LocationsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  GuestNetworks
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Guest Networks API
 *
 * This is the public API for the [Guest Networks platform](https://www.mywifinetworks.com).  All requests must include an App Secret Key for authentication. To get your App Secret Key: 1. Log in to your MyWiFi Control Panel 1. Navigate to Branding section 1. Note your API key, located in the App Secret Key field   <br/> # Available SDKs [PHP API Client](https://github.com/MyWiFiNetworks/PublicAPI-PHP)
 *
 * OpenAPI spec version: 1.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.19
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace GuestNetworks;

use GuestNetworks\Configuration;
use GuestNetworks\ApiException;
use GuestNetworks\ObjectSerializer;

/**
 * LocationsApiTest Class Doc Comment
 *
 * @category Class
 * @package  GuestNetworks
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class LocationsApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for assignCampaign
     *
     * Assign Default Campaign to Location.
     *
     */
    public function testAssignCampaign()
    {
    }

    /**
     * Test case for assignDevice
     *
     * Assign Device to Location.
     *
     */
    public function testAssignDevice()
    {
    }

    /**
     * Test case for createOrUpdateLocation
     *
     * Create or Update a Location.
     *
     */
    public function testCreateOrUpdateLocation()
    {
    }

    /**
     * Test case for deleteLocation
     *
     * Delete a Location.
     *
     */
    public function testDeleteLocation()
    {
    }

    /**
     * Test case for getLocation
     *
     * Retrieve data for multiple or single Location(s).
     *
     */
    public function testGetLocation()
    {
    }

    /**
     * Test case for getLocationDevices
     *
     * List all Devices assigned to Location.
     *
     */
    public function testGetLocationDevices()
    {
    }

    /**
     * Test case for getLocationOptions
     *
     * Retrieve Location Options / Settings [RADIUS Attributes].
     *
     */
    public function testGetLocationOptions()
    {
    }

    /**
     * Test case for locationList
     *
     * Retrieve list of all Locations.
     *
     */
    public function testLocationList()
    {
    }

    /**
     * Test case for updateLocationOptions
     *
     * Update Location Options / Settings [RADIUS Attributes].
     *
     */
    public function testUpdateLocationOptions()
    {
    }
}
